---
config:

  generator:
    generate: True
#    seed: 1
    dynamic_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/dynamic3.txt"
    static_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/static3.txt"
    N: 200
    L: 70
    W: 20
    mass: 1
    r0: 1
    dr: 0.15
    vx: 0
    vy: 0

  simulator:
    results_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/results2.txt"
    exit_time_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/exitTime2.txt"
    dynamic_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/dynamic3.txt"
    static_file: "/Users/frbernad/PROGRAMMING/ITBA/SS/TPs/TP5/results/static3.txt"
#    seed: 1
    L: 70
    W: 20
    vx: 0
    vy: 0
    dt: 0.001
    dt2: 0.1
    tf: 1000
    D: 3
    A: 0.15
    w: 5
    kn: 250
    kt: 500
    reenter_min_height: 40
    reenter_max_height: 70
    exit_distance: 7
    gravity: 5



...